### PR TITLE
LPS-120425 [TS]

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @georgel-pop-lr 

could you please check my fix and push it forward?

Thanks, Roland

https://issues.liferay.com/browse/LPS-120425

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr
> 
> could you please check my fix and push it forward?
> 
> Thanks, Roland
> 
> https://issues.liferay.com/browse/LPS-120425

Hi,
Will have a look into it.

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
Just started reviewing :)

**Comment by georgel-pop-lr** [comment]
Close this PR continuing here https://github.com/georgel-pop-lr/liferay-portal/pull/3

**Pull request closed without merging**
