### PR TITLE
LPS-135935 Override calendarbase header template to meet accessibility criteria

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi @georgel-pop-lr ,

Accessibility tool (Accessibility Insights for Web) detected error on minicalendar heading element and insufficient color contrast on the weekdays.
The header template is actually coming from the YUI library, but since that was not updated for a long time and the fix is small, I was advised to override the template in the calendar-web module.
LPS: https://issues.liferay.com/browse/LPS-135935

Please review. Thanks!

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Hi @orsolyaDekany,

After your fixes, I still see one fail:
image

Is happening on your side?

Regards.

**Comment by georgel-pop-lr** [comment]
I will close this PR until the remaining fail is getting fixed as well.

Regards.

**Pull request closed without merging**
