### PR TITLE
[TS] LPS-144294 Introduce configurable build identifier instead of build number in static resource URLs

### PR DESCRIPTION
**Pull request by istvansajtos**
Dear Georgel,

I got the information that Antonio is on PTO for a longer period. I hope you are the right person to send my PR to.

You can find all the necessary information on the LPS and related PTR.

Please let me know if you have any questions or concerns.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Hi @istvansajtos,

These changes are not related to Front-end Infra components and needs to be reviewed by Core Infrastructure team.

You need to check the SME for Core Infrastructure here: https://grow.liferay.com/people/SME+Master+List (seems to be Minhchau Dang or Eric Yan)

I will close this pull.

Regards,

**Comment by istvansajtos** [comment]
Thanks @georgel-pop-lr ! Sorry if this doesn't belong to you. As the issue is about static resource caching, I though maybe front-end team should validate. 

I sent a new PR to Eric Yan: https://github.com/ericyanLr/liferay-portal/pull/255

**Pull request closed without merging**
