### PR TITLE
[TECHNICAL SUPPORT] LPS-135460 delta parameter is missing from the url if pagination is done trough combo box

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-135460](https://issues.liferay.com/browse/LPS-135460),
This issue is a regression of [LPS-134536](https://issues.liferay.com/browse/LPS-134536), In case of the asset publisher we store the delta parameter in the portlet configuration, however with the changes introduced in LPS-134546, I stripped down the delta parameter from the url, and it causes issues in simple scenarios, where a customer is using this taglib in their custom portlet.

I reworked the solution to update the parameter in the url instead of stripping it completely, please  review my changes

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
Hey @georgel-pop-lr , could you take a look on the changes please?

Thanks

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
LGTM

Send to the team.

https://github.com/liferay-frontend/liferay-portal/pull/1252

Regards.

**Pull request closed without merging**
