### PR TITLE
LPS-134536

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @georgel-pop-lr ,

Can you have a look at this, please?

Original comment from @NemethNorbert

> Hello,
> 
> LPS-134536,
> There was an additional parameter from the current page on the items' url. I stripped it down and it resolved the issue.
> Please review my change.
> 
> Thanks,

@NemethNorbert For future pull requests, you can send them to @georgel-pop-lr , please.

Thanks.

Regards.

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr ,
> 
> Can you have a look at this, please?
> 
> Original comment from @NemethNorbert
> 
> > Hello,
> > LPS-134536,
> > There was an additional parameter from the current page on the items' url. I stripped it down and it resolved the issue.
> > Please review my change.
> > Thanks,
> 
> @NemethNorbert For future pull requests, you can send them to @georgel-pop-lr , please.
> 
> Thanks.
> 
> Regards.

Hi @antonio-ortega @NemethNorbert,

Having a look now. 

Regards.

**Comment by georgel-pop-lr** [comment]
> > Hi @georgel-pop-lr ,
> > Can you have a look at this, please?
> > Original comment from @NemethNorbert
> > > Hello,
> > > LPS-134536,
> > > There was an additional parameter from the current page on the items' url. I stripped it down and it resolved the issue.
> > > Please review my change.
> > > Thanks,
> > 
> > 
> > @NemethNorbert For future pull requests, you can send them to @georgel-pop-lr , please.
> > Thanks.
> > Regards.
> 
> Hi @antonio-ortega @NemethNorbert,
> 
> Having a look now.
> 
> Regards.

Hi @NemethNorbert,

One question, is this problem affecting master or only 7.2.x?

Because I tried to reproduce it on master, but I'm not able to.

Regards.

**Comment by NemethNorbert** [comment]
> > > Hi @georgel-pop-lr ,
> > > Can you have a look at this, please?
> > > Original comment from @NemethNorbert
> > > > Hello,
> > > > LPS-134536,
> > > > There was an additional parameter from the current page on the items' url. I stripped it down and it resolved the issue.
> > > > Please review my change.
> > > > Thanks,
> > > 
> > > 
> > > @NemethNorbert For future pull requests, you can send them to @georgel-pop-lr , please.
> > > Thanks.
> > > Regards.
> > 
> > 
> > Hi @antonio-ortega @NemethNorbert,
> > Having a look now.
> > Regards.
> 
> Hi @NemethNorbert,
> 
> One question, is this problem affecting master or only 7.2.x?
> 
> Because I tried to reproduce it on master, but I'm not able to.
> 
> Regards.

Hey @georgel-pop-lr ,
The issue is reproducible on master as well.

Thanks,

**Comment by georgel-pop-lr** [comment]
Closing as was send to Product team: https://github.com/liferay-frontend/liferay-portal/pull/1191

**Pull request closed without merging**
