### PR TITLE
[TS] LPS-135935 Improve accessibility in Calendar widget

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi @georgel-pop-lr ,
previous PR: https://github.com/georgel-pop-lr/liferay-portal/pull/18

Accessibility tool (Accessibility Insights for Web) detected a few errors:
- invalid aria attribute on minicalendar heading element
- insufficient color contrast on the weekdays
- missing aria attribute on the parent element of views (scheduler-base-views)

LPS: https://issues.liferay.com/browse/LPS-135935

Please review my fixes. Thanks!

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by orsolyaDekany** [comment]
Hi @georgel-pop-lr , I updated the PR. Please review it. Thank you!

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr , I updated the PR. Please review it. Thank you!

Hi @orsolyaDekany,

I will review it today, as I was on holidays yesterday.

Regards.

**Comment by georgel-pop-lr** [comment]
Send to frontend team: https://github.com/liferay-frontend/liferay-portal/pull/1546

**Pull request closed without merging**
