### PR TITLE
[TS] LPS-120425 | Date picker shows year as 'y' when using JDK11 for language Arabic/Laos/Persian/Slovenian

### PR DESCRIPTION
**Pull request by rolandpakai**
Description:
Date picker shows year as 'y' when using JDK11 for language Arabic/Laos/Persian/Slovenian

Steps to reproduce:
1. Use JRE/JDK 11 for the reproduction
2. Start a master bundle
3. Set the user's language to Arabic/Laos/Persian/Slovenian
4. Set the user's birthday by clicking on the date field

Before this PR: Year is shown as 'y', can't set any other year than 2020
After this PR: Year should be shown with numbers, should be able to set any date

For more details: https://issues.liferay.com/browse/LPS-120425

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
Just started reviewing :)

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
Hi @rolandpakai,
Now it works and the tests looks good, so from my side the review is considered successful, I will push this to https://github.com/liferay-frontend/liferay-portal so the frontend engineering team is able to verify it and pushing to master.
Regards.

**Comment by rolandpakai** [comment]
Thank you @georgel-pop-lr

**Pull request closed without merging**
