### PR TITLE
[TS] LPS-120425 

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-120425 Fixing date format when using JAVA 11 with replacing y mask to %y
https://issues.liferay.com/browse/LPS-120425

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Just started reviewing :)

**Comment by georgel-pop-lr** [comment]
Hi @rolandpakai,

I have checked your solution with Arabic language but is not working properly, is displaying 2070 and is not possible to save this date as birthday because in the future. I guess something is still missing in the format.
Can you please check why is this happening ? 

Regards. 

image

**Comment by georgel-pop-lr** [comment]
> Hi @rolandpakai,
> 
> I have checked your solution with Arabic language but is not working properly, is displaying 2070 and is not possible to save this date as birthday because is in the future. I guess something is still missing in the format.
> Can you please check why is this happening ?
> 
> Regards.
> 
> image

My guess is that it should be replaced by: mask = mask.replaceAll("y", "%Y");
image

**Comment by rolandpakai** [comment]
Hi @georgel-pop-lr 

thanks for checking my change.
I tested it with the Arabic language too and for me works.

1. For me the dateformat is yyyy/mm/dd
2. The mask is %d?/%m?/%Y in the input_date/page.jsp

Could you please check it again?


image


Thanks, Roland

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr
> 
> thanks for checking my change.
> I tested it with the Arabic language too and for me works.
> 
> 1. The date format is yyyy/mm/dd
> 2. The mask is %d?/%m?/%Y in the input_date/page.jsp
> 
> Could you please check it again?
> 
> image
> 
> Thanks, Roland

Try this steps:
1. Have English as display language 
2. Set user birthday to 01.01.1970 
3. Change language to Arabic 
4. Check user birthday is 01.01.2070
Let me know if these steps are working for you.

**Comment by rolandpakai** [comment]
Hi @georgel-pop-lr 

i retested with your steps, and for me the birthday date is 1970/01/01

Roland

**Comment by rolandpakai** [comment]
Oh, i known whats wrong: i forget to change to JRE11
I will retest it now.

**Comment by rolandpakai** [comment]
Okey. After setting JRE11 i can not still reproduce it.
After changing to Arabic language the date is 1970/01/01
And i can save the 1970/01/01 

But i have issue with the Slovenian language. After chaging the birthday date i can not save the date because of invalid date.
I will check this.

**Comment by rolandpakai** [comment]
Resent: https://github.com/georgel-pop-lr/liferay-portal/pull/5

**Comment by georgel-pop-lr** [comment]
> Resent: #5

Okay, closing this one.

**Pull request closed without merging**
