### PR TITLE
[TS] LPS-142123 Empty button and link error on widget and content page - accessibility

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi @georgel-pop-lr ,

https://issues.liferay.com/browse/LPS-142123
The issue is that Wave accessibility tool detected empty button and empty links on Widget and Content page.
I have added aria-label attribute to the elements.

Please review my changes,
Thank you!

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
Hi @orsolyaDekany, 

These changes look okay from my side, could you please send them to liferay-frontend team for review?

Regards.

**Comment by orsolyaDekany** [comment]
forwarded: https://github.com/liferay-frontend/liferay-portal/pull/1658

**Pull request closed without merging**
