### PR TITLE
LPS-138363 Disabled checkbox does not send data in request

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Continuing here...

/cc @laszlopap

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Hi @laszlopap,

Did you observe that now you are able to change Active checkbox input? 
I think this should be disabled, and we need to look for a different approach.

image

From what I understand, the problem is that a disabled input is not being sent with the form? 

Maybe we can send this information with another hidden input.

Let me know what you think.

Regards.

**Comment by laszlopap** [comment]
hi @georgel-pop-lr !

I will check the method you suggested.

**Pull request closed without merging**
